const translations = {
    en: {
        nav_download: "Download App",
        hero_title1: "Grade Smarter, Not Harder.",
        hero_title2: "Your AI Grading Assistant.",
        hero_subtitle: "Gradaly is an intelligent desktop grading assistant that accelerates handwritten exam grading using Google Gemini multimodal AI, while keeping teachers fully in control of every mark.",
        download_mac: "Download for macOS",
        see_how: "See how it works",
        phil_title: "Our Philosophy",
        phil_text: "Grading is tedious and repetitive. Teachers spend countless hours tallying points instead of providing valuable feedback. Gradaly doesn't replace the teacher; it acts as a smart assistant looking over your shoulder. By automating visual recognition and rubric matching with Gemini, you reclaim your time to provide meaningful, personalized feedback where it truly matters.",
        
        adv_title: "Why choose Gradaly?",
        adv1_title: "Clean Desktop App",
        adv1_text: "Built with Tauri 2.0 and Rust. Ultra-fast, lightweight, and operates natively on macOS, Windows and Linux without distracting clutter.",
        adv2_title: "Bring Your Own AI",
        adv2_text: "Powered by Google's top multimodal Gemini models (3.8 Flash, 3.7 Flash, 3.1 Pro). Direct connection with your own Google Gemini API key.",
        adv_privacy_title: "Total Privacy & Zero Cloud",
        adv_privacy_text: "A student's name never leaves your computer. The CSV roster, header OCR and copy matching run 100% offline locally. Only cropped answer snippets defined in the canvas are sent to the AI, ensuring complete student anonymity.",
        adv_cost_title: "Direct Cost Control",
        adv_cost_text: "You own your API Key. The application takes zero margin—whether you grade 10 or 1000 copies, you only pay direct AI provider costs (fractions of a cent per copy).",
        adv_control_title: "You Have the Final Say",
        adv_control_text: "Gradaly is a grading assistant, not a replacement. You retain full, fine-grained control and can overwrite the AI's output on any copy ergonomically at any moment.",
        adv_flex_title: "Dynamic Recalculation",
        adv_flex_text: "Change a rubric weighting or adjust base points at any time: all student scores across the entire cohort are automatically recalculated on the fly.",

        // Carousel slides
        carousel_slide0_badge: "Step 1: Canvas & Rubrics",
        carousel_slide0_title: "Layout, MAX_SCORE & Criteria",
        carousel_slide0_desc: "Delineate the student ID zone for offline OCR, configure question answer boxes, set individual MAX_SCORE limits with automatic capping, and write custom AI prompts.",
        
        carousel_slide1_badge: "Step 2: Students",
        carousel_slide1_title: "Import Student Roster (CSV)",
        carousel_slide1_desc: "Load your enrolled class list (matricule IDs, names, emails). Student data remains 100% confidential and stored locally on your machine.",
        
        carousel_slide2_badge: "Step 3: Matching",
        carousel_slide2_title: "Automatic & Manual Copy Matching",
        carousel_slide2_desc: "Batch import scanned student copies. Local offline OCR matches each copy to the student record, with 1-click manual verification.",
        
        carousel_slide3_badge: "Step 4: Workspace",
        carousel_slide3_title: "Unified Grading Console",
        carousel_slide3_desc: "Navigate copies smoothly with a high-performance PDF viewer, switchable anonymous mode, rubric checklist, and direct access to Pro exports.",
        
        carousel_slide4_badge: "Step 5: Batch AI",
        carousel_slide4_title: "Launch AI Grading Across Copies",
        carousel_slide4_desc: "Select which questions and copies to grade using Google Gemini (3.8 Flash, 3.7 Flash, 3.1 Pro), with options to evaluate unrated copies or overwrite.",
        
        carousel_slide5_badge: "Step 5 (cont.): Progress",
        carousel_slide5_title: "Real-Time AI Execution & Feedback",
        carousel_slide5_desc: "Follow the multimodal AI in real time as it ticks validated criteria and drafts constructive feedback. You maintain full sovereignty to override anything.",
        
        carousel_slide6_badge: "Step 6: Analytics",
        carousel_slide6_title: "Cohort Statistics & Clarified Histograms",
        carousel_slide6_desc: "Track grade distributions and rubric success rates in real time. Histograms feature unambiguous interval notation [a, b) with hover inequalities.",
        
        carousel_slide7_badge: "PRO Feature: Annotated Copies",
        carousel_slide7_title: "Individual Student PDF Reports (ZIP)",
        carousel_slide7_desc: "Export all graded copies in one ZIP archive! Each student receives a print-friendly PDF featuring an executive summary cover sheet and interleaved corrections.",

        // Guide / User Guide Section
        guide_title: "Gradaly User Guide: From Rubric to Grade Export",
        guide_subtitle: "Gradaly simplifies and accelerates exam grading with the power of Gemini models, while keeping teachers in full control of every decision.",

        guide_step1_tag: "Step 1",
        guide_step1_title: "Evaluation Canvas Setup",
        guide_step1_subtitle: "Before importing student copies, prepare your exam structure on the blank PDF:",
        guide_step1_item1_title: "Identification Area:",
        guide_step1_item1_desc: "Delineate the reserved box for student details (name, first name, ID/matricule).",
        guide_step1_item2_title: "Question Layout:",
        guide_step1_item2_desc: "Add exam questions by drawing bounding boxes over the respective answer regions.",
        guide_step1_item3_title: "Criteria, Rubric & MAX_SCORE:",
        guide_step1_item3_desc: "Define additive criteria (0.5 pt increments), set individual question MAX_SCORE limits with automatic capping, and ensure rubric consistency.",
        guide_step1_item4_title: "Evaluation Logic (Prompt):",
        guide_step1_item4_desc: "Write a dedicated grading prompt per question to guide the AI (key expectations, tolerances, required steps).",

        guide_step2_tag: "Step 2",
        guide_step2_title: "Import Student Roster",
        guide_step2_subtitle: "Load your enrolled class list to prepare tracking and export:",
        guide_step2_item1_title: "CSV File:",
        guide_step2_item1_desc: "Import student records (matricule IDs, last names, first names, email addresses, groups).",
        guide_step2_item2_title: "Secure Local Reference:",
        guide_step2_item2_desc: "This roster stays 100% on your computer and serves as the official reference for matching copies.",

        guide_step3_tag: "Step 3",
        guide_step3_title: "Import Copies & Matching",
        guide_step3_subtitle: "Batch drop files and seamlessly connect them to students:",
        guide_step3_item1_title: "Batch PDF Drop:",
        guide_step3_item1_desc: "Import your scanned student exam PDF copies all at once.",
        guide_step3_item2_title: "Automatic Matching (100% Offline):",
        guide_step3_item2_desc: "Using a private on-device OCR algorithm, Gradaly inspects the identification box and matches each copy to the student record.",
        guide_step3_item3_title: "Ergonomic Manual Adjustment:",
        guide_step3_item3_desc: "If handwriting is ambiguous, inspect high-resolution zoomed headers and assign students in a single click.",

        guide_step4_tag: "Step 4",
        guide_step4_title: "AI-Assisted Grading & Human Control",
        guide_step4_subtitle: "The core strength of Gradaly:",
        guide_step4_item1_title: "Gemini Multimodal Analysis:",
        guide_step4_item1_desc: "The AI examines the student's handwritten answer according to your prompt, selects met criteria and suggests an instant score.",
        guide_step4_item2_title: "Constructive Feedback:",
        guide_step4_item2_desc: "Gradaly generates a personalized constructive comment explaining errors and successes to the student.",
        guide_step4_item3_title: "Complete Teacher Sovereignty:",
        guide_step4_item3_desc: "The AI is strictly an advisory assistant. The teacher remains the sole decision-maker: easily override, toggle criteria or polish comments.",

        guide_step5_tag: "Step 5",
        guide_step5_title: "Dynamic Analytics & Grade Export",
        guide_step5_subtitle: "Monitor progress and distribute grades with ease:",
        guide_step5_item1_title: "Statistics & Clarified Histograms:",
        guide_step5_item1_desc: "Monitor completion rates, review cohort distributions with unambiguous interval brackets [a, b), and check criterion success rates.",
        guide_step5_item2_title: "Real-time Flexibility:",
        guide_step5_item2_desc: "Adjust rubric points, base marks, or question weights at any moment; the entire cohort recalculates dynamically.",
        guide_step5_item3_title: "Multi-Sheet Excel Export (PRO):",
        guide_step5_item3_desc: "Export comprehensive spreadsheets (summary with student IDs, names, emails, plus individual question sheets) ready for school administration.",
        guide_step5_item4_title: "Annotated Student PDFs in ZIP (PRO):",
        guide_step5_item4_desc: "Generate print-friendly individual PDF copies for each student with an executive summary cover sheet and interleaved corrections.",

        // Privacy Callout
        privacy_banner_title: "Local Architecture & Student Anonymity",
        privacy_banner_badge: "100% Offline",
        privacy_banner_desc: "A student's name never leaves your computer. The CSV student roster, header OCR, and copy matching operate entirely locally on your machine. Only cropped answer snippets defined in the canvas are sent to the AI via your own Gemini API key, ensuring students cannot be identified when the canvas is properly configured.",

        // Download & Gatekeeper
        download_mac: "Download for macOS",
        download_windows: "Download for Windows",
        download_linux: "Download for Linux",
        download_appimage: "Download .AppImage",
        download_deb: "Download .deb",
        download_sub: "Universal (Apple Silicon M1-M4 & Intel)",
        download_sub_mac: "Apple Silicon (M1-M4) & Intel",
        download_sub_windows: "Windows 10, 11 (64-bit)",
        download_sub_linux: "Ubuntu 22.04+, Debian 12+, Fedora",
        macos_req: "Requires macOS 11.0 or later",
        windows_req: "Requires Windows 10/11 (64-bit)",
        linux_req: "Requires 64-bit Linux (x86_64 or ARM64)",
        windows_badge: "64-bit Installer (.exe)",
        apple_notarized_badge: "Official Apple Developer Signed & Notarized",
        gatekeeper_btn: "Security & Installation info (macOS & Windows)",
        gatekeeper_title: "Security & Signature info",
        gatekeeper_desc: "On macOS, Gradaly is officially signed with an Apple Developer ID and notarized by Apple. On Windows, double-click the installer; if Windows Defender SmartScreen appears on first run, click 'More info' then 'Run anyway'.",
        gatekeeper_fix_title: "Quick start:",
        gatekeeper_step1: "Open the downloaded .dmg and drag Gradaly to Applications.",
        gatekeeper_step2: "Double-click Gradaly to launch. If prompted by macOS, click 'Open'.",
        gatekeeper_step3: "Launch Gradaly anytime from your Applications folder!",
        copy: "Copy",
        copied: "Copied!",
        cta_subtitle: "Join the teachers who have already reclaimed their weekends.",
        footer_rights: "All rights reserved.",

        // Pricing
        nav_pricing: "Pricing",
        pricing_tag: "Transparent Pricing",
        pricing_title: "Start Free, Upgrade for Multi-Sheet Excel & Annotated PDFs",
        pricing_subtitle: "Grade all your exams with AI for free. Support Gradaly and unlock official multi-sheet Excel exports and individual annotated student PDF packages with Gradaly Pro.",
        plan_free_name: "Gradaly Community",
        plan_free_badge: "Free Forever",
        plan_free_period: "/ free",
        plan_free_f1: "All AI models (Gemini Flash, Pro...)",
        plan_free_f2: "Unlimited students & exam copies",
        plan_free_f3: "100% offline student OCR & matching",
        plan_free_f4: "Live grading console & human control",
        plan_free_f5: "Cohort analytics & score histograms",
        plan_free_btn: "Download for Free",
        plan_pro_name: "Gradaly Pro",
        plan_pro_badge: "Recommended",
        plan_pro_period: "/ year",
        plan_pro_f1: "Unlimited Multi-Sheet Excel Export",
        plan_pro_f2: "Individual Annotated Student PDFs (ZIP Archive)",
        plan_pro_f3: "Print-friendly cover sheet with grade & question breakdown",
        plan_pro_f4: "License valid on all your machines (macOS, Windows, Linux)",
        plan_pro_f5: "Priority developer support & all future Pro updates",
        plan_pro_btn: "Get Gradaly Pro (29.99 € / yr)",
    },
    fr: {
        nav_download: "Télécharger l'App",
        hero_title1: "Corrigez plus intelligemment.",
        hero_title2: "Votre assistant IA pour la correction.",
        hero_subtitle: "Gradaly est un assistant de bureau intelligent qui simplifie et accélère la correction de copies d'examens manuscrites grâce à l'IA multimodale Google Gemini, tout en laissant l'enseignant aux commandes de chaque décision.",
        download_mac: "Télécharger pour macOS",
        see_how: "Voir le fonctionnement",
        phil_title: "Notre Philosophie",
        phil_text: "La correction est souvent fastidieuse et répétitive. Les enseignants passent des heures à compter des points au lieu d'apporter un retour pédagogique utile. Gradaly ne remplace pas l'enseignant ; il agit comme un assistant intelligent qui regarde par-dessus votre épaule. En automatisant la reconnaissance visuelle et la vérification des barèmes avec Gemini, vous gagnez un temps précieux pour offrir des retours personnalisés là où cela compte vraiment.",
        
        adv_title: "Pourquoi choisir Gradaly ?",
        adv1_title: "Application Bureau Native",
        adv1_text: "Conçue avec Tauri 2.0 et Rust. Ultra-rapide, légère, autonome et multiplateforme (macOS, Windows, Linux) sans distraction.",
        adv2_title: "Apportez votre IA (BYOAI)",
        adv2_text: "Propulsée par les meilleurs modèles multimodaux de Google (Gemini 3.8 Flash, 3.7 Flash, 3.1 Pro). Connexion directe avec votre propre clé API Gemini.",
        adv_privacy_title: "Confidentialité Absolue & Zéro Cloud",
        adv_privacy_text: "Le nom d'un étudiant ne sort jamais de votre ordinateur. Le trombinoscope CSV, l'OCR des en-têtes et l'appariement des copies s'exécutent intégralement en local. Seuls des fragments de copies partent vers l'IA, ne permettant en aucun cas d'identifier l'étudiant.",
        adv_cost_title: "Maîtrise Totale des Coûts",
        adv_cost_text: "Vous êtes propriétaire de votre clé API. L'application ne prend aucune marge : que vous corrigiez 10 ou 1000 copies, vous payez uniquement le coût direct fournisseur (quelques fractions de centime par copie).",
        adv_control_title: "Vous Gardez le Dernier Mot",
        adv_control_text: "Gradaly est une aide à la correction, pas un remplaçant. L'enseignant conserve un contrôle ergonomique et absolu : validez, modifiez ou écrasez la proposition de l'IA en un clic.",
        adv_flex_title: "Recalcul Dynamique",
        adv_flex_text: "Modifiez la pondération d'un critère ou la note de base à tout moment : l'ensemble des scores de la promotion est automatiquement recalculé à la volée.",

        // Carousel slides
        carousel_slide0_badge: "Étape 1 : Canevas & Barème",
        carousel_slide0_title: "Découpage, MAX_SCORE & Critères",
        carousel_slide0_desc: "Délimitez la zone d'en-tête pour l'OCR local, cadrez les questions, fixez le score maximum par question (MAX_SCORE) avec plafonnement automatique et consignes IA.",
        
        carousel_slide1_badge: "Étape 2 : Étudiants",
        carousel_slide1_title: "Import du Trombinoscope (CSV)",
        carousel_slide1_desc: "Chargez votre liste de classe (matricules, noms, emails). Aucune donnée nominative ne sort de votre machine : confidentialité 100% garantie.",
        
        carousel_slide2_badge: "Étape 3 : Appariement",
        carousel_slide2_title: "Appariement Automatique & Manuel",
        carousel_slide2_desc: "Importez vos copies PDF en lot. L'OCR local hors-ligne inspecte la zone d'en-tête manuscrite et associe chaque copie à son étudiant en un clic.",
        
        carousel_slide3_badge: "Étape 4 : Visualiseur",
        carousel_slide3_title: "Poste d'Évaluation Ergonomique",
        carousel_slide3_desc: "Parcourez les copies avec un visualiseur haute résolution, un mode anonyme commutable, la validation des critères et l'accès direct aux exports Pro.",
        
        carousel_slide4_badge: "Étape 5 : IA par lot",
        carousel_slide4_title: "Lancement de la Correction IA",
        carousel_slide4_desc: "Sélectionnez les questions et copies à évaluer avec Gemini (3.8 Flash, 3.7 Flash, 3.1 Pro), avec option d'évaluer les copies restantes ou tout réévaluer.",
        
        carousel_slide5_badge: "Étape 5 (suite) : Exécution",
        carousel_slide5_title: "Suivi en Direct & Retours Détaillés",
        carousel_slide5_desc: "Observez l'analyse multimodale en temps réel. Gemini coche les critères mérités et formule un commentaire constructif que l'enseignant valide ou modifie.",
        
        carousel_slide6_badge: "Étape 6 : Synthèse",
        carousel_slide6_title: "Statistiques & Histogrammes Clairs",
        carousel_slide6_desc: "Suivez la moyenne, la médiane et le taux de succès par critère. Les histogrammes utilisent des tranches explicites [a, b[ levant toute ambiguïté sur les bornes.",
        
        carousel_slide7_badge: "Fonctionnalité PRO : Copies Annotées",
        carousel_slide7_title: "Export PDF Individuel avec Page de Garde",
        carousel_slide7_desc: "Exportez l'ensemble des copies dans une archive ZIP ! Chaque étudiant reçoit un PDF optimisé pour l'impression avec page de garde récapitulative et corrections entrelacées.",

        // Guide / User Guide Section
        guide_title: "Guide d'utilisation de Gradaly : Du barème à l'export des notes",
        guide_subtitle: "Gradaly simplifie et accélère la correction des copies grâce à la puissance des modèles Gemini, tout en laissant l'enseignant aux commandes de chaque décision.",

        guide_step1_tag: "Étape 1",
        guide_step1_title: "Configuration du Canevas d'évaluation",
        guide_step1_subtitle: "Avant d'importer les copies, préparez la structure de votre épreuve :",
        guide_step1_item1_title: "Zone d'identification :",
        guide_step1_item1_desc: "Délimitez l'emplacement réservé aux informations de l'étudiant (nom, prénom, identifiant).",
        guide_step1_item2_title: "Découpage des questions :",
        guide_step1_item2_desc: "Ajoutez les questions de l'examen en traçant leurs zones de réponse sur le PDF vierge.",
        guide_step1_item3_title: "Critères, Barème & MAX_SCORE :",
        guide_step1_item3_desc: "Définissez précisément les critères d'évaluation (multiples de 0,5 pt), fixez le score maximum par question (MAX_SCORE) avec plafonnement automatique des points.",
        guide_step1_item4_title: "Logique de correction (Prompt) :",
        guide_step1_item4_desc: "Rédigez une consigne d'évaluation dédiée par question pour guider l'IA (attentes clés, tolérances, éléments indispensables).",

        guide_step2_tag: "Étape 2",
        guide_step2_title: "Import du référentiel étudiants",
        guide_step2_subtitle: "Chargez votre liste de classe pour préparer le suivi :",
        guide_step2_item1_title: "Fichier CSV :",
        guide_step2_item1_desc: "Importez les données de vos étudiants (identifiants, noms, adresses email, groupes).",
        guide_step2_item2_title: "Référence locale sécurisée :",
        guide_step2_item2_desc: "Ce fichier constitue la référence pour l'association ultérieure des copies et reste 100% stocké en local sur votre ordinateur.",

        guide_step3_tag: "Étape 3",
        guide_step3_title: "Import des copies et appariement (Matching)",
        guide_step3_subtitle: "Dépôt des fichiers et liaison automatique :",
        guide_step3_item1_title: "Dépôt des fichiers :",
        guide_step3_item1_desc: "Importez les PDF des copies d'étudiants scannées en lot.",
        guide_step3_item2_title: "Appariement automatique 100% hors-ligne :",
        guide_step3_item2_desc: "Grâce à un algorithme intelligent d'OCR local (0% cloud), Gradaly analyse la zone d'identification et relie automatiquement chaque copie à l'étudiant correspondant issu de votre fichier CSV.",
        guide_step3_item3_title: "Ajustement manuel :",
        guide_step3_item3_desc: "Si un doute persiste ou si l'écriture est illisible, vous pouvez finaliser l'appariement manuellement en quelques clics grâce à l'aperçu zoomé en haute résolution.",

        guide_step4_tag: "Étape 4",
        guide_step4_title: "Évaluation assistée par IA & Contrôle humain",
        guide_step4_subtitle: "C'est la force de Gradaly :",
        guide_step4_item1_title: "Analyse par Gemini :",
        guide_step4_item1_desc: "L'IA examine la réponse de l'étudiant selon vos instructions, sélectionne les critères validés et calcule une proposition de note.",
        guide_step4_item2_title: "Feedback constructif :",
        guide_step4_item2_desc: "Gradaly génère un retour explicatif personnalisé pour aider l'étudiant à comprendre ses erreurs et ses réussites.",
        guide_step4_item3_title: "Maîtrise totale par le correcteur :",
        guide_step4_item3_desc: "L'IA est un outil de support et d'aide à la décision. L'enseignant reste l'unique décideur : vous pouvez corriger manuellement, valider, modifier les critères sélectionnés ou retoucher le commentaire en toute liberté.",

        guide_step5_tag: "Étape 5",
        guide_step5_title: "Pilotage dynamique et Exportation",
        guide_step5_subtitle: "Supervision analytique et diffusion :",
        guide_step5_item1_title: "Statistiques & Histogrammes clairs :",
        guide_step5_item1_desc: "Visualisez l'état d'avancement de votre correction et analysez les performances globales (histogrammes avec tranches [a, b[ rigoureuses, taux de succès par critère).",
        guide_step5_item2_title: "Recalcul dynamique :",
        guide_step5_item2_desc: "Repondérez des questions, ajustez le barème ou la note de base à tout moment ; l'ensemble des scores est recalculé dynamiquement.",
        guide_step5_item3_title: "Export Excel multi-feuilles (PRO) :",
        guide_step5_item3_desc: "Exportez l'ensemble des résultats (feuille récapitulative officielle et feuilles ordonnées par question) prêt pour votre scolarité.",
        guide_step5_item4_title: "Archive ZIP de copies PDF annotées (PRO) :",
        guide_step5_item4_desc: "Générez un ensemble de fichiers PDF individuels print-friendly avec page de garde récapitulative et pages de copie entrelacées.",

        // Privacy Callout
        privacy_banner_title: "Architecture locale & Anonymat des étudiants",
        privacy_banner_badge: "100% Hors-ligne",
        privacy_banner_desc: "Le nom d'un étudiant ne sort jamais de votre ordinateur. Le trombinoscope CSV, l'OCR des en-têtes et l'appariement des copies s'exécutent intégralement en local sur votre machine. Seuls des fragments de copies délimités dans le canevas partent vers l'IA via votre propre clé API Gemini, ne permettant en aucun cas d'identifier l'étudiant si le canevas a bien été configuré.",

        // Download & Gatekeeper
        download_mac: "Télécharger pour macOS",
        download_windows: "Télécharger pour Windows",
        download_linux: "Télécharger pour Linux",
        download_appimage: "Télécharger .AppImage",
        download_deb: "Télécharger .deb",
        download_sub: "Universel (Apple Silicon M1-M4 & Intel)",
        download_sub_mac: "Apple Silicon (M1-M4) & Intel",
        download_sub_windows: "Windows 10, 11 (64-bit)",
        download_sub_linux: "Ubuntu 22.04+, Debian 12+, Fedora",
        macos_req: "Requis : macOS 11.0 ou ultérieur",
        windows_req: "Requis : Windows 10/11 (64-bit)",
        linux_req: "Requis : Linux 64-bit (x86_64 ou ARM64)",
        windows_badge: "Installateur 64-bit (.exe)",
        apple_notarized_badge: "Certifié & Notarisé par Apple",
        gatekeeper_btn: "Informations de sécurité & installation (macOS & Windows)",
        gatekeeper_title: "Sécurité, Certificats & Lancement",
        gatekeeper_desc: "Sous macOS, Gradaly est officiellement signé avec un certificat Apple Developer ID Application et notarisé par Apple. Sous Windows, lancez l'installateur .exe ; si l'écran bleu Windows SmartScreen apparaît lors de la première ouverture, cliquez simplement sur « Informations complémentaires » puis « Exécuter quand même ».",
        gatekeeper_fix_title: "Démarrage rapide :",
        gatekeeper_step1: "Ouvrez le .dmg téléchargé et glissez Gradaly dans Applications.",
        gatekeeper_step2: "Double-cliquez pour ouvrir. Si macOS demande confirmation, cliquez simplement sur « Ouvrir ».",
        gatekeeper_step3: "Lancez Gradaly à tout moment depuis votre dossier Applications !",
        copy: "Copier",
        copied: "Copié !",
        cta_subtitle: "Rejoignez les enseignants qui ont déjà récupéré leurs week-ends.",
        footer_rights: "Tous droits réservés.",

        // Pricing
        nav_pricing: "Tarifs",
        pricing_tag: "Tarification Claire",
        pricing_title: "Commencez gratuitement, passez à Pro pour Excel et les PDFs",
        pricing_subtitle: "Corrigez tous vos examens avec l'IA gratuitement. Soutenez le développement et débloquez l'export Excel officiel ainsi que les copies PDF annotées avec Gradaly Pro.",
        plan_free_name: "Gradaly Gratuit",
        plan_free_badge: "Gratuit à vie",
        plan_free_period: "/ gratuit",
        plan_free_f1: "Tous les modèles IA (Gemini Flash, Pro...)",
        plan_free_f2: "Copies et étudiants illimités",
        plan_free_f3: "OCR et appariement trombinoscope 100% hors-ligne",
        plan_free_f4: "Console de correction live & contrôle humain total",
        plan_free_f5: "Statistiques complètes et histogrammes de notes",
        plan_free_btn: "Télécharger gratuitement",
        plan_pro_name: "Gradaly Pro",
        plan_pro_badge: "Recommandé",
        plan_pro_period: "/ an (TTC)",
        plan_pro_f1: "Exportation Excel multi-feuilles illimitée",
        plan_pro_f2: "Archive ZIP de toutes les copies PDF annotées",
        plan_pro_f3: "Page de garde récapitulative élégante (note, synthèse par question)",
        plan_pro_f4: "Licence valide sur toutes vos machines (macOS, Windows, Linux)",
        plan_pro_f5: "Mises à jour Pro et support prioritaire",
        plan_pro_btn: "Passer à Gradaly Pro (29,99 € / an)",
    }
};

document.addEventListener('alpine:init', () => {
    Alpine.data('i18n', () => ({
        lang: 'en',
        t: {},
        init() {
            // Check browser language or saved preference
            const userLang = navigator.language || navigator.userLanguage; 
            if(userLang.startsWith('fr')) {
                this.lang = 'fr';
            }
            this.updateTranslations();
        },
        toggleLang() {
            this.lang = this.lang === 'en' ? 'fr' : 'en';
            this.updateTranslations();
        },
        updateTranslations() {
            this.t = translations[this.lang];
        }
    }));
});
