const translations = {
    en: {
        nav_download: "Download App",
        hero_version_badge: "Latest release available:",
        cta_version_info: "Current release:",
        hero_title1: "Grade Smarter, Not Harder.",
        hero_title2: "Your AI Grading Assistant.",
        hero_subtitle: "Spend your time designing a fine-grained, high-quality rubric rather than grading repetitively. Gradaly applies your criteria with AI, lets you instantly simulate the impact of adjustments across the entire cohort, and keeps you fully in control of every grade.",
        download_mac: "Download for macOS",
        see_how: "See how it works",
        phil_title: "Our Philosophy",
        phil_text: "Repetitive grading is exhausting and adds little pedagogical value. Teachers spend countless hours tallying marks instead of exercising pedagogical judgment. Gradaly shifts your time and expertise to where they truly matter: designing a rigorous, fine-grained evaluation rubric. By delegating systematic criteria checking to AI, you can easily simulate the impact of changing weights or criteria across the whole cohort, re-run grading in one click, and dedicate your energy to providing meaningful, personalized feedback to your students.",
        
        adv_title: "Why choose Gradaly?",
        adv_pedagogy_title: "Pedagogical Focus & Rubric Design",
        adv_pedagogy_text: "Invest your expertise in designing nuanced, high-standard evaluation rubrics instead of doing repetitive manual grading. AI systematically applies your criteria to every single copy.",
        adv_flex_title: "Dynamic Recalculation & Simulation",
        adv_flex_text: "Adjust a rubric weighting, tweak criteria, or change the base points: instantly observe the impact across the entire cohort or re-run grading in one click to test your evaluation scenarios.",
        adv_control_title: "You Have the Final Say",
        adv_control_text: "Gradaly is an assistant, not a replacement. The teacher retains full, sovereign control: validate, adjust criteria, or overwrite feedback with a single click.",
        adv_privacy_title: "Total Privacy & Zero Cloud",
        adv_privacy_text: "A student's name never leaves your computer. The CSV student roster, header inspection, and copy matching run 100% offline locally. Only cropped, anonymous answer snippets are analyzed by the AI.",
        adv1_title: "Native Desktop Experience",
        adv1_text: "Ultra-fast, lightweight, and responsive. Operates directly on your machine (macOS, Windows, Linux) with high-performance PDF rendering and zero browser lag.",
        adv_cost_title: "100% Direct & Transparent Costs",
        adv_cost_text: "You own your Google Gemini API key. The application takes zero margin—grade 100% free with Google's Free Tier (safe 15 RPM rate limiting), or choose Flex/Standard tiers for fractions of a cent per copy.",

        // Carousel slides (8-step pipeline)
        carousel_slide0_badge: "Step 1: Create Project",
        carousel_slide0_title: "Start a New Project or Try the Demo",
        carousel_slide0_desc: "Create an exam project in seconds, or immediately explore the built-in demo projects to discover the entire workflow with ready-made copies.",
        
        carousel_slide1_badge: "Step 2: Import Canvas",
        carousel_slide1_title: "Load Blank Exam PDF & Student ID Zone",
        carousel_slide1_desc: "Import your blank exam master sheet. Delineate the header box (name, student ID) for private offline OCR, and set global prompt instructions.",
        
        carousel_slide2_badge: "Step 3: Questions & Rubric",
        carousel_slide2_title: "Frame Zones, Criteria & Fine-Grained Rubrics",
        carousel_slide2_desc: "Draw bounding boxes over answer areas. Set maximum scores, create additive grading criteria (+0.5 pt, +1 pt...), and write AI prompt guidelines with live LaTeX preview.",
        
        carousel_slide3_badge: "Step 4: Student Roster",
        carousel_slide3_title: "Import Official Class Roster (CSV)",
        carousel_slide3_desc: "Load your enrolled students list (matricule IDs, names, emails, groups). All student records remain 100% confidential and local (zero cloud) on your computer.",
        
        carousel_slide4_badge: "Step 5: Copies & Matching",
        carousel_slide4_title: "Batch Import Scans & Automatic Matching",
        carousel_slide4_desc: "Drop student exam PDF scans in batch or split a multi-copy document. On-device local OCR inspects handwritten headers and links each copy to its student.",
        
        carousel_slide5_badge: "Step 6: Grading (AI or Manual)",
        carousel_slide5_title: "AI Pre-Grading, Manual, or Hybrid Evaluation",
        carousel_slide5_desc: "Grade questions with Gemini (Free Tier 15 RPM or Standard) with selective override protection (grades, feedback, justifications). Inspect, adjust by hand, or grade fully manually.",
        
        carousel_slide6_badge: "Step 7: Statistics & Insights",
        carousel_slide6_title: "Mean, Median, Spread & Clear Histograms",
        carousel_slide6_desc: "Review cohort score distributions, question performance, criterion success rates, and bracketed histograms [a, b). Simulate rubric changes in real time across all copies.",
        
        carousel_slide7_badge: "Step 8: Export or Adjust",
        carousel_slide7_title: "Export Excel, PDFs, Web Portal or Adjust Rubrics",
        carousel_slide7_desc: "Satisfied with your marks? Export the official multi-sheet Excel gradebook, individual annotated student PDFs, or the AES-256 encrypted Student Web Portal. Or adjust rubrics freely!",

        // Guide / User Guide Section (8-Step Pipeline)
        guide_title: "Gradaly User Guide: The 8-Step Evaluation Pipeline",
        guide_subtitle: "From project setup to grade delivery, discover how Gradaly accelerates exam grading while preserving total human sovereignty and student privacy.",

        guide_step1_tag: "Step 1",
        guide_step1_title: "Create Project & Workspace",
        guide_step1_subtitle: "Start fresh or explore with built-in examples:",
        guide_step1_item1_title: "Project Management:",
        guide_step1_item1_desc: "Create an isolated workspace folder with automatic version migration and history.",
        guide_step1_item2_title: "Instant Demos:",
        guide_step1_item2_desc: "Load complete French or English demo projects with 20 real student copies in 1 click.",

        guide_step2_tag: "Step 2",
        guide_step2_title: "Import Exam Canvas PDF",
        guide_step2_subtitle: "Load your blank subject sheet and set student privacy boundaries:",
        guide_step2_item1_title: "Blank Exam Subject:",
        guide_step2_item1_desc: "Import the official PDF master copy used as the geometric coordinate reference for all student copies.",
        guide_step2_item2_title: "Student Identification Box:",
        guide_step2_item2_desc: "Delineate the header box where students write their name and matricule ID for 100% offline OCR.",

        guide_step3_tag: "Step 3",
        guide_step3_title: "Define Questions, Zones & Rubrics",
        guide_step3_subtitle: "Craft fine-grained pedagogical evaluation rubrics:",
        guide_step3_item1_title: "Answer Bounding Boxes:",
        guide_step3_item1_desc: "Draw rectangular boxes around each question across multi-page exams.",
        guide_step3_item2_title: "Criteria & Maximum Score:",
        guide_step3_item2_desc: "Set additive criteria (0.5 pt increments) and individual question max scores with automatic capping.",
        guide_step3_item3_title: "AI Prompt Guidance & KaTeX:",
        guide_step3_item3_desc: "Configure feedback tone, toggleable LaTeX formatting, and specific grading directives with live math preview.",

        guide_step4_tag: "Step 4",
        guide_step4_title: "Import Student Roster",
        guide_step4_subtitle: "Load your enrolled class list to prepare automated matching:",
        guide_step4_item1_title: "CSV / Spreadsheet Import:",
        guide_step4_item1_desc: "Import matricule IDs, names, emails, and student groups with flexible column mapping.",
        guide_step4_item2_title: "100% Local & Confidential:",
        guide_step4_item2_desc: "Student identities remain strictly on your machine and never touch any cloud server.",

        guide_step5_tag: "Step 5",
        guide_step5_title: "Import Copies & Automated Matching",
        guide_step5_subtitle: "Drop student scans and match them automatically to your roster:",
        guide_step5_item1_title: "Batch PDF Drop or Split:",
        guide_step5_item1_desc: "Drop pre-split student PDFs or cut a combined batch exam scan directly in Gradaly.",
        guide_step5_item2_title: "Offline Header OCR Matching:",
        guide_step5_item2_desc: "Private local OCR reads handwritten student names and links copies to the official roster.",
        guide_step5_item3_title: "1-Click Manual Adjustment:",
        guide_step5_item3_desc: "Easily inspect high-resolution zoomed headers if handwriting is ambiguous and assign students in 1 click.",

        guide_step6_tag: "Step 6",
        guide_step6_title: "Grading: AI, Manual, or Hybrid",
        guide_step6_subtitle: "Speed up correction while retaining complete human pedagogical authority:",
        guide_step6_item1_title: "Gemini Multimodal Analysis:",
        guide_step6_item1_desc: "The AI analyzes handwriting against your rubric, checks criteria, and suggests a score.",
        guide_step6_item2_title: "Selective Override Protection:",
        guide_step6_item2_desc: "Protect existing grades, feedback, or justifications when re-running AI on already graded copies.",
        guide_step6_item3_title: "Ergonomic Manual Grading:",
        guide_step6_item3_desc: "Inspect question by question with student sorting, 1-click criteria checkboxes, and live feedback.",

        guide_step7_tag: "Step 7",
        guide_step7_title: "Review Statistics & Cohort Insights",
        guide_step7_subtitle: "Real-time promotion KPIs, spread analysis, and criteria success:",
        guide_step7_item1_title: "Mean, Median & Std Dev:",
        guide_step7_item1_desc: "Track class performance metrics and distribution moments calculated dynamically.",
        guide_step7_item2_title: "Clarified Histograms [a, b):",
        guide_step7_item2_desc: "Visualize score brackets with unambiguous interval notation and interactive hover tooltips.",
        guide_step7_item3_title: "Rubric Success Rates:",
        guide_step7_item3_desc: "Identify questions and sub-criteria where students struggled to inform future teaching.",

        guide_step8_tag: "Step 8",
        guide_step8_title: "Export Results or Adjust Rubrics",
        guide_step8_subtitle: "Multi-sheet Excel, annotated PDFs, and Zero-Knowledge Web Portal:",
        guide_step8_item1_title: "Multi-Sheet Excel (PRO):",
        guide_step8_item1_desc: "Official summary sheet with student IDs, names, emails, plus dedicated tabs per question ready for administration.",
        guide_step8_item2_title: "Annotated Student PDFs (PRO):",
        guide_step8_item2_desc: "Individual exam sheets with cover summaries, validated rubrics, and interleaved notes in a single ZIP archive.",
        guide_step8_item3_title: "Zero-Knowledge Student Web Portal (PRO):",
        guide_step8_item3_desc: "Generate a self-hosted static site encrypted with AES-256-GCM. 100% GDPR compliant with 1-click magic links.",
        guide_step8_item4_title: "Dynamic Rubric Adjustment:",
        guide_step8_item4_desc: "Not satisfied with the curve? Adjust criterion points and weights: all student scores recalculate dynamically!",

        // Privacy Callout
        privacy_banner_title: "Local Architecture & Student Anonymity",
        privacy_banner_badge: "100% Offline",
        privacy_banner_desc: "A student's name never leaves your computer. The CSV student roster, header OCR, and copy matching operate entirely locally on your machine. Only cropped answer snippets defined in the canvas are sent to the AI via your own Gemini API key, ensuring students cannot be identified when the canvas is properly configured.",

        // Download & Gatekeeper
        download_mac: "Download for macOS",
        download_windows: "Download for Windows",
        download_linux: "Download for Linux",
        download_rpm: "Download .rpm",
        download_deb: "Download .deb",
        download_appimage: "Download .AppImage",
        download_sub: "Universal (Apple Silicon M1-M4 & Intel)",
        download_sub_mac: "Apple Silicon (M1-M4) & Intel",
        download_sub_windows: "Windows 10, 11 (64-bit)",
        download_sub_linux: "Fedora, Ubuntu, Debian, RHEL, openSUSE",
        macos_req: "Requires macOS 11.0 or later (Universal)",
        windows_req: "Requires Windows 10/11 (64-bit)",
        linux_req: "Built on Ubuntu 22.04 LTS (glibc 2.35+) • Tested on Fedora 39/40 & Ubuntu 22.04/24.04",
        windows_badge: "64-bit Installer (.exe)",
        apple_notarized_badge: "Official Apple Developer Signed & Notarized",
        linux_fedora_badge: "Fedora 38+ (.rpm)",
        linux_ubuntu_badge: "Ubuntu / Debian (.deb)",
        gatekeeper_btn: "Installation & Compatibility instructions (macOS, Windows, Fedora, Ubuntu)",
        gatekeeper_title: "OS Compatibility & Installation Guide",
        gatekeeper_desc: "Installation guidelines and system requirements for each supported operating system:",
        install_mac_title: "macOS (Apple Silicon & Intel)",
        install_mac_text: "Gradaly is officially signed with an Apple Developer ID and notarized by Apple. Open the downloaded .dmg and drag Gradaly to your Applications folder.",
        install_win_title: "Windows 10 / 11",
        install_win_text: "Run the .exe installer. If Windows Defender SmartScreen appears on first run, click 'More info' then 'Run anyway'.",
        install_fedora_title: "Fedora / RHEL / openSUSE (.rpm)",
        install_fedora_text: "Download the .rpm package and run: sudo dnf install ./gradaly-x86_64.rpm. DNF will automatically install all required dependencies (including WebKitGTK 4.1).",
        install_ubuntu_title: "Ubuntu / Debian (.deb)",
        install_ubuntu_text: "Download the .deb package and run: sudo apt install ./gradaly-amd64.deb.",
        install_appimage_title: "Universal Linux (.AppImage)",
        install_appimage_text: "Run chmod +x Gradaly-Linux.AppImage && ./Gradaly-Linux.AppImage. Note: Fedora 38+ and Ubuntu 24.04 do not ship legacy FUSE2 by default; if prompted, run sudo dnf install fuse (Fedora) or sudo apt install libfuse2 (Ubuntu), or use the native .rpm / .deb package instead.",
        install_build_info: "Linux build environment: x86_64 binaries are built in an Ubuntu 22.04 LTS runner with glibc 2.35 (and ARM64 under Ubuntu 24.04). Fully compatible with any distribution providing glibc ≥ 2.35.",
        copy: "Copy",
        copied: "Copied!",
        cta_subtitle: "Provide your students with richer, clearer, and truly formative feedback.",
        footer_rights: "All rights reserved.",

        // Student Portal Section (Pro Showcase)
        nav_student_portal: "Student Portal",
        portal_badge: "Pro Feature Exclusive",
        portal_title: "Zero-Knowledge Student Consultation Portal",
        portal_subtitle: "Return 200 graded copies in minutes with zero paper printing and zero bulk emailing: Gradaly generates a self-hosted, confidential web viewer where each student interacts with their personal annotated copy and rubric.",
        portal_b1_title: "Seamless Formative Distribution",
        portal_b1_desc: "In one click, export a complete static web folder and an Excel/CSV spreadsheet listing every student alongside their personal 1-click magic link, ready for automated mail merge or direct LMS distribution.",
        portal_b2_title: "100% Host-Independent & Private",
        portal_b2_desc: "Gradaly does not host your student data. You freely upload the static files to any hosting space of your choice (university web space, Cloudflare Pages, Netlify). Each copy is locked with a unique key: students can never see each other's work.",
        portal_b3_title: "Interactive Student Experience",
        portal_b3_desc: "Students explore their copy question-by-question with crisp handwriting scans, delineated bounding boxes, validated criteria checklist, teacher feedback with KaTeX math rendering, and a downloadable PDF.",
        portal_demo_pill: "Interactive Live Demo",
        portal_demo_title: "Experience What Your Students See",
        portal_demo_desc: "Click either demo exam below to open the live student consultation viewer. Test client-side AES-256 decryption, interactive rubric toggling, and question bounding boxes directly in your browser.",
        portal_btn_demo_fr: "Open French Demo Copy (Emma Dubois — 19.8 / 20)",
        portal_btn_demo_en: "Open English Demo Copy (Emma Dubois — 19.8 / 20)",
        portal_demo_note: "Both demo copies decrypt 100% in your browser using the Web Crypto API. No data is sent over the wire.",
        portal_tech_accordion_title: "Security, Hosting & Zero-Knowledge Architecture (Click to expand)",
        portal_tech_q1_title: "Where and how do I host the generated portal?",
        portal_tech_q1_desc: "Gradaly does not provide hosting so that you remain 100% in control of your data and infrastructure. The app produces a static folder (index.html and an encrypted data/ directory) requiring zero database, zero PHP, and zero server maintenance. You can drag-and-drop it to Cloudflare Pages (free), Netlify Drop (free), GitHub Pages, or upload it to your university department web server via WebDAV or SFTP.",
        portal_tech_q2_title: "How does client-side Zero-Knowledge encryption work?",
        portal_tech_q2_desc: "Every student copy is encrypted locally on your machine using AES-256-GCM with a cryptographically secure random key. The hosting server only stores unintelligible encrypted payloads (.enc). Neither the web host nor anyone intercepting the files can read the exam papers.",
        portal_tech_q3_title: "Why does the 1-click magic link never leak the secret key?",
        portal_tech_q3_desc: "The magic link is formatted as index.html?id=...#k=SECRET_KEY. By worldwide W3C/IETF standards (RFC 3986), the URL fragment following the hash symbol (#) is strictly local to the student's browser and is NEVER transmitted in HTTP request headers. The key decrypts the copy in RAM only.",

        // Pricing
        nav_pricing: "Pricing",
        pricing_tag: "Transparent Pricing",
        pricing_title: "Start Free, Upgrade for Multi-Sheet Excel & Student Portal",
        pricing_subtitle: "Grade all your exams with AI for free. Support Gradaly and unlock official multi-sheet Excel exports, individual student PDF archives, and the Zero-Knowledge Student Web Portal with Gradaly Pro.",
        plan_free_name: "Gradaly Community",
        plan_free_badge: "Free Forever",
        plan_free_period: "/ free",
        plan_free_f1: "Gemini 3.8 & 3.7 Flash with Free Tier mode",
        plan_free_f2: "Unlimited students & exam copies",
        plan_free_f3: "100% offline student OCR & matching",
        plan_free_f4: "Live grading console & human control",
        plan_free_f5: "Cohort analytics & score histograms",
        plan_free_f6: "Evaluation exports (1-copy test for Excel, PDF and Web portal)",
        plan_free_btn: "Download for Free",
        plan_pro_name: "Gradaly Pro",
        plan_pro_badge: "Recommended",
        plan_pro_period: "/ year",
        plan_pro_f1: "Zero-Knowledge Student Web Portal (full class, self-hosted)",
        plan_pro_f2: "Unlimited Multi-Sheet Excel Export",
        plan_pro_f3: "Individual Annotated Student PDFs (ZIP Archive)",
        plan_pro_f4: "Print-friendly cover sheet with grade & question breakdown",
        plan_pro_f5: "License valid on all your machines (macOS, Windows, Linux)",
        plan_pro_f6: "Priority developer support & all future Pro updates",
        plan_pro_btn: "Get Gradaly Pro (29.99 € / yr)",
    },
    fr: {
        nav_download: "Télécharger l'App",
        hero_version_badge: "Dernière version disponible :",
        cta_version_info: "Version actuelle :",
        hero_title1: "Mieux Corriger, Pour Mieux Former.",
        hero_title2: "Votre assistant IA pour la correction.",
        hero_subtitle: "Consacrez votre temps à concevoir un barème d'évaluation fin et rigoureux plutôt qu'à corriger de manière répétitive. Gradaly applique vos critères avec l'IA, simule immédiatement l'impact de vos ajustements sur toute la promotion et vous laisse toujours le dernier mot.",
        download_mac: "Télécharger pour macOS",
        see_how: "Voir le fonctionnement",
        phil_title: "Notre Philosophie",
        phil_text: "Corriger des copies de manière répétitive est épuisant et n'apporte que peu de valeur ajoutée. Gradaly permet à l'enseignant de déplacer son temps et son expertise là où ils comptent le plus : la conception d'un barème d'évaluation fin, juste et formateur. En confiant l'application systématique des critères à l'IA, vous pouvez tester vos barèmes, ajuster vos pondérations ou relancer une correction en mesurant immédiatement l'impact sur l'ensemble de la classe, et vous concentrer sur l'essentiel : les retours constructifs apportés à vos étudiants.",
        
        adv_title: "Pourquoi choisir Gradaly ?",
        adv_pedagogy_title: "Focus Pédagogique & Barème Fin",
        adv_pedagogy_text: "Consacrez votre expertise à la conception d'un barème d'évaluation fin, juste et exigeant plutôt qu'à répéter les mêmes gestes mécaniques. L'IA applique rigoureusement vos critères sur chaque copie.",
        adv_flex_title: "Simulation & Recalcul Dynamique",
        adv_flex_text: "Modifiez la pondération d'un critère, ajustez le barème ou la note de base : visualisez immédiatement l'impact sur toute la promotion ou relancez la correction en un clic pour tester vos scénarios.",
        adv_control_title: "Vous Gardez le Dernier Mot",
        adv_control_text: "Gradaly est une aide à la décision, pas un remplaçant. L'enseignant conserve un contrôle absolu : validez, modifiez un critère ou réécrivez un commentaire en un seul clic.",
        adv_privacy_title: "Confidentialité Absolue & Données Locales",
        adv_privacy_text: "Le nom d'un étudiant ne sort jamais de votre ordinateur. La liste des étudiants (CSV), la lecture des en-têtes et l'appariement des copies s'exécutent intégralement en local. Seuls des extraits de copies anonymisés sont analysés par l'IA.",
        adv1_title: "Application de Bureau Fluide",
        adv1_text: "Ultra-rapide, légère et réactive. S'exécute directement sur votre ordinateur (macOS, Windows, Linux) avec un affichage PDF haute performance, sans lenteur de navigateur ni distraction.",
        adv_cost_title: "Coûts Directs & Transparents",
        adv_cost_text: "Vous utilisez directement votre propre clé API Gemini sans intermédiaire. L'application ne prend aucune marge : corrigez gratuitement avec le mode Free Tier de Google (sécurisé à 15 RPM), ou optez pour les modes Flex/Standard pour quelques fractions de centime.",

        // Carousel slides (pipeline en 8 étapes)
        carousel_slide0_badge: "Étape 1 : Créer le projet",
        carousel_slide0_title: "Créer un projet ou lancer une démo",
        carousel_slide0_desc: "Démarrez un nouveau projet d'examen en un clic, ou explorez immédiatement les projets de démonstration intégrés pour découvrir le flux de correction complet.",
        
        carousel_slide1_badge: "Étape 2 : Importer le canevas",
        carousel_slide1_title: "PDF vierge & Zone d'identification",
        carousel_slide1_desc: "Chargez le PDF de votre sujet d'examen vierge. Délimitez la zone d'en-tête (nom, prénom, matricule) pour l'OCR 100% local et configurez les directives générales du prompt IA.",
        
        carousel_slide2_badge: "Étape 3 : Questions & Barèmes",
        carousel_slide2_title: "Tracer les zones, critères & barèmes",
        carousel_slide2_desc: "Cadrez les zones de réponse sur le canevas. Fixez le score maximal, définissez vos critères fins (+0,5 pt, +1 pt...) et affinez vos consignes de correction avec rendu LaTeX en direct.",
        
        carousel_slide3_badge: "Étape 4 : Importer les étudiants",
        carousel_slide3_title: "Importer la liste des étudiants (CSV)",
        carousel_slide3_desc: "Chargez la liste officielle de votre promotion (matricules, noms, emails, groupes). Vos données nominatives restent 100% locales et confidentielles (zéro cloud) sur votre machine.",
        
        carousel_slide4_badge: "Étape 5 : Importer les copies",
        carousel_slide4_title: "Import des scans & appariement automatique",
        carousel_slide4_desc: "Déposez vos scans de copies d'examen en lot ou découpez un scan groupé. L'OCR local hors-ligne inspecte les en-têtes manuscrits et relie automatiquement chaque copie à l'étudiant correspondant.",
        
        carousel_slide5_badge: "Étape 6 : Notation des copies",
        carousel_slide5_title: "Notation IA, manuelle ou mixte",
        carousel_slide5_desc: "Déléguez la pré-correction à Gemini (Free Tier 15 RPM ou Standard) avec contrôle fin des écrasements (notes, feedback, justifications). Contrôlez, ajustez à la main ou notez en toute autonomie.",
        
        carousel_slide6_badge: "Étape 7 : Consulter les statistiques",
        carousel_slide6_title: "Moyenne, médiane & histogrammes précis",
        carousel_slide6_desc: "Analysez la distribution des notes de la promotion, le taux de réussite par critère et les histogrammes à tranches [a, b[. Simulez vos ajustements de barème instantanément.",
        
        carousel_slide7_badge: "Étape 8 : Exporter ou adapter",
        carousel_slide7_title: "Excel, PDF annotés, Portail Web ou ajustements",
        carousel_slide7_desc: "Satisfait de vos notes ? Exportez en 1 clic le tableur Excel officiel, les copies annotées en PDF, ou le Portail Web Zéro-Knowledge chiffré en AES-256. Sinon, ajustez vos barèmes à volonté !",

        // Guide / User Guide Section (Pipeline en 8 étapes)
        guide_title: "Guide d'utilisation de Gradaly : Le pipeline en 8 étapes",
        guide_subtitle: "De la création du projet à la restitution des copies, découvrez comment Gradaly accélère vos corrections tout en préservant votre souveraineté pédagogique et la confidentialité des étudiants.",

        guide_step1_tag: "Étape 1",
        guide_step1_title: "Création du Projet & Espace de travail",
        guide_step1_subtitle: "Démarrez un nouveau projet ou découvrez Gradaly avec les démos :",
        guide_step1_item1_title: "Gestion de projet :",
        guide_step1_item1_desc: "Créez un dossier de travail dédié avec migration automatique des versions et historique.",
        guide_step1_item2_title: "Projets de démonstration :",
        guide_step1_item2_desc: "Chargez en 1 clic un projet démo complet (en français ou en anglais) avec 20 copies corrigées.",

        guide_step2_tag: "Étape 2",
        guide_step2_title: "Importation du Canevas d'Examen",
        guide_step2_subtitle: "Chargez votre sujet d'examen vierge et cadrez la zone d'identification :",
        guide_step2_item1_title: "Sujet vierge :",
        guide_step2_item1_desc: "Importez le PDF officiel de l'examen servant de référence géométrique pour toutes les copies.",
        guide_step2_item2_title: "Zone d'identification :",
        guide_step2_item2_desc: "Délimitez le cadre où l'étudiant inscrit son nom et matricule pour l'OCR 100% hors-ligne.",

        guide_step3_tag: "Étape 3",
        guide_step3_title: "Configuration des Questions, Zones & Barèmes",
        guide_step3_subtitle: "Construisez votre barème d'évaluation avec précision :",
        guide_step3_item1_title: "Cadrage des zones de réponse :",
        guide_step3_item1_desc: "Tracez les cadres rectangulaires autour de chaque question sur toutes les pages de l'épreuve.",
        guide_step3_item2_title: "Critères fins & Plafonnement :",
        guide_step3_item2_desc: "Définissez des critères additifs (paliers de 0,5 pt) et plafonnez automatiquement la note maximale.",
        guide_step3_item3_title: "Directives IA & Rendu KaTeX :",
        guide_step3_item3_desc: "Ajustez le ton des commentaires, le formatage LaTeX commutable et vos consignes avec prévisualisation des formules.",

        guide_step4_tag: "Étape 4",
        guide_step4_title: "Import de la Liste des Étudiants",
        guide_step4_subtitle: "Chargez votre liste de classe pour préparer l'attribution des copies :",
        guide_step4_item1_title: "Import CSV universel :",
        guide_step4_item1_desc: "Importez matricules, noms, emails et groupes avec détection automatique des colonnes.",
        guide_step4_item2_title: "Confidentialité 100% locale :",
        guide_step4_item2_desc: "Les données d'identité restent strictement sur votre ordinateur et ne transitent jamais sur le cloud.",

        guide_step5_tag: "Étape 5",
        guide_step5_title: "Import des Copies & Appariement",
        guide_step5_subtitle: "Déposez les scans et associez chaque copie à son étudiant :",
        guide_step5_item1_title: "Dépôt par lot ou découpage :",
        guide_step5_item1_desc: "Déposez vos PDF individuels ou découpez un gros PDF multipages scanné en une seule passe.",
        guide_step5_item2_title: "Appariement OCR hors-ligne :",
        guide_step5_item2_desc: "L'OCR local lit les écritures manuscrites dans l'en-tête et relie chaque copie à son étudiant.",
        guide_step5_item3_title: "Vérification manuelle en 1 clic :",
        guide_step5_item3_desc: "Vérifiez d'un coup d'œil les en-têtes zoomés en haute résolution pour les écritures difficiles.",

        guide_step6_tag: "Étape 6",
        guide_step6_title: "Notation des Copies : IA, Manuelle ou Mixte",
        guide_step6_subtitle: "Accélérez la correction tout en gardant une souveraineté pédagogique absolue :",
        guide_step6_item1_title: "Pré-correction par Gemini :",
        guide_step6_item1_desc: "L'IA analyse les réponses manuscrites, sélectionne les critères validés et calcule une note.",
        guide_step6_item2_title: "Protection fine contre l'écrasement :",
        guide_step6_item2_desc: "Préservez sélectivement vos notes, feedback ou justifications lors d'une nouvelle passe de l'IA.",
        guide_step6_item3_title: "Poste d'évaluation fluide :",
        guide_step6_item3_desc: "Naviguez question par question avec tri par note, validation de critères en 1 clic et feedback en direct.",

        guide_step7_tag: "Étape 7",
        guide_step7_title: "Consultation des Statistiques & Synthèse",
        guide_step7_subtitle: "KPIs de promotion, dispersion des notes et taux de succès par question :",
        guide_step7_item1_title: "Moyenne, Médiane & Écart-type :",
        guide_step7_item1_desc: "Suivez la moyenne, la médiane et l'écart-type de la classe calculés dynamiquement.",
        guide_step7_item2_title: "Histogrammes rigoureux [a, b[ :",
        guide_step7_item2_desc: "Visualisez les tranches de notes avec notation d'intervalles claire et infobulles détaillées.",
        guide_step7_item3_title: "Taux de réussite par critère :",
        guide_step7_item3_desc: "Identifiez les questions et compétences où les étudiants ont buté pour adapter vos cours.",

        guide_step8_tag: "Étape 8",
        guide_step8_title: "Exportation des Résultats ou Ajustements",
        guide_step8_subtitle: "Tableur Excel, PDF individuels et Portail Web Zéro-Knowledge :",
        guide_step8_item1_title: "Tableur Excel multi-feuilles (PRO) :",
        guide_step8_item1_desc: "Feuille de synthèse officielle enrichie du trombinoscope, avec un onglet par question.",
        guide_step8_item2_title: "Copies PDF annotées en ZIP (PRO) :",
        guide_step8_item2_desc: "PDF individuels complets avec page de garde récapitulative et barème détaillé.",
        guide_step8_item3_title: "Portail Web Étudiant Zéro-Knowledge (PRO) :",
        guide_step8_item3_desc: "Site web statique chiffré AES-256-GCM, sans serveur ni risque cloud, avec liens magiques 1-clic.",
        guide_step8_item4_title: "Ajustement & simulation libre :",
        guide_step8_item4_desc: "Pas satisfait de la répartition ? Ajustez barèmes et critères : toutes les notes se recalculent instantanément !",

        // Privacy Callout
        privacy_banner_title: "Architecture locale & Anonymat des étudiants",
        privacy_banner_badge: "100% Hors-ligne",
        privacy_banner_desc: "Le nom d'un étudiant ne sort jamais de votre ordinateur. La liste des étudiants (CSV), la lecture des en-têtes et l'appariement des copies s'exécutent intégralement en local sur votre machine. Seuls des fragments de copies délimités dans le canevas partent vers l'IA via votre propre clé API Gemini, ne permettant en aucun cas d'identifier l'étudiant si le canevas a bien été configuré.",

        // Download & Gatekeeper
        download_mac: "Télécharger pour macOS",
        download_windows: "Télécharger pour Windows",
        download_linux: "Télécharger pour Linux",
        download_rpm: "Télécharger .rpm",
        download_deb: "Télécharger .deb",
        download_appimage: "Télécharger .AppImage",
        download_sub: "Universel (Apple Silicon M1-M4 & Intel)",
        download_sub_mac: "Apple Silicon (M1-M4) & Intel",
        download_sub_windows: "Windows 10, 11 (64-bit)",
        download_sub_linux: "Fedora, Ubuntu, Debian, RHEL, openSUSE",
        macos_req: "Requis : macOS 11.0 ou ultérieur (Universel)",
        windows_req: "Requis : Windows 10/11 (64-bit)",
        linux_req: "Compilé sous Ubuntu 22.04 LTS (glibc 2.35+) • Testé sur Fedora 39/40 & Ubuntu 22.04/24.04",
        windows_badge: "Installateur 64-bit (.exe)",
        apple_notarized_badge: "Certifié & Notarisé par Apple",
        linux_fedora_badge: "Fedora 38+ (.rpm)",
        linux_ubuntu_badge: "Ubuntu / Debian (.deb)",
        gatekeeper_btn: "Consignes d'installation & Compatibilité (macOS, Windows, Fedora, Ubuntu)",
        gatekeeper_title: "Compatibilité des Systèmes & Guide d'Installation",
        gatekeeper_desc: "Retrouvez les instructions d'installation pour chaque système d'exploitation :",
        install_mac_title: "macOS (Apple Silicon & Intel)",
        install_mac_text: "Gradaly est officiellement signé avec un certificat Apple Developer ID et notarisé par Apple. Ouvrez le .dmg téléchargé et glissez Gradaly dans votre dossier Applications.",
        install_win_title: "Windows 10 / 11",
        install_win_text: "Lancez l'installateur .exe. Si l'écran bleu Windows SmartScreen apparaît à la première ouverture, cliquez sur « Informations complémentaires » puis « Exécuter quand même ».",
        install_fedora_title: "Fedora / RHEL / openSUSE (.rpm)",
        install_fedora_text: "Téléchargez le paquet .rpm et installez-le avec : sudo dnf install ./gradaly-x86_64.rpm. DNF installera automatiquement toutes les dépendances système nécessaires (notamment WebKitGTK 4.1).",
        install_ubuntu_title: "Ubuntu / Debian (.deb)",
        install_ubuntu_text: "Téléchargez le paquet .deb et installez-le avec : sudo apt install ./gradaly-amd64.deb.",
        install_appimage_title: "Linux Universel (.AppImage)",
        install_appimage_text: "Rendez le fichier exécutable avec chmod +x Gradaly-Linux.AppImage puis lancez-le. Si vous êtes sous Fedora 38+ ou Ubuntu 24.04 et rencontrez une erreur liée à FUSE, installez le support avec sudo dnf install fuse (Fedora) ou sudo apt install libfuse2 (Ubuntu), ou préférez directement le paquet natif .rpm / .deb.",
        install_build_info: "Environnement de compilation Linux : Les binaires x86_64 sont compilés sous Ubuntu 22.04 LTS (glibc 2.35) et ARM64 sous Ubuntu 24.04. Compatibles avec toute distribution Linux récente intégrant glibc ≥ 2.35.",
        copy: "Copier",
        copied: "Copié !",
        cta_subtitle: "Offrez à vos étudiants un feedback plus riche, plus précis et véritablement formateur.",
        footer_rights: "Tous droits réservés.",

        // Student Portal Section (Pro Showcase)
        nav_student_portal: "Portail Étudiant",
        portal_badge: "Fonctionnalité Pro Exclusive",
        portal_title: "Portail de Restitution Étudiant Zéro-Knowledge",
        portal_subtitle: "Rendez 200 copies corrigées en quelques minutes sans aucune impression papier ni envoi d'emails lourds : Gradaly génère un portail web interactif et confidentiel où chaque étudiant consulte sa copie et son barème.",
        portal_b1_title: "Restitution Pédagogique Immédiate",
        portal_b1_desc: "En 1 clic, exportez un site web statique complet ainsi qu'un tableau Excel/CSV associant chaque étudiant à son lien magique personnel, prêt pour un publipostage ou une diffusion sur votre LMS (Moodle, Teams).",
        portal_b2_title: "Hébergement 100% libre & Zéro Cloud",
        portal_b2_desc: "Gradaly n'héberge pas vos données pour préserver votre indépendance. Vous déposez librement les fichiers statiques où vous voulez (serveur de votre université, Cloudflare Pages, Netlify). Chaque copie est verrouillée : aucun étudiant ne peut voir celle d'un camarade.",
        portal_b3_title: "Consultation étudiante interactive",
        portal_b3_desc: "L'étudiant navigue question par question avec le scan haute définition de son écriture manuscrite, le cadre de la question, le barème détaillé, les critères validés, vos explications avec formules KaTeX et le PDF téléchargeable.",
        portal_demo_pill: "Démonstration Interactive en Direct",
        portal_demo_title: "Testez ce que voit votre étudiant",
        portal_demo_desc: "Cliquez sur l'une des deux copies d'examen ci-dessous pour ouvrir le visualiseur étudiant sécurisé. Expérimentez le déchiffrement local instantané, la navigation par question et le barème en direct dans votre navigateur.",
        portal_btn_demo_fr: "Consulter la copie Démo FR (Emma Dubois — 19.8 / 20)",
        portal_btn_demo_en: "Consulter la copie Démo EN (Emma Dubois — 19.8 / 20)",
        portal_demo_note: "Les deux copies sont déchiffrées 100% localement dans votre navigateur via l'API Web Crypto. Aucune donnée n'est transmise sur le réseau.",
        portal_tech_accordion_title: "Détails techniques, Hébergement & Architecture Zéro-Knowledge (Cliquer pour dérouler)",
        portal_tech_q1_title: "Où et comment héberger le site web généré ?",
        portal_tech_q1_desc: "Gradaly n'offre pas d'hébergement afin que vous restiez 100% souverain sur vos données et votre infrastructure. L'application produit un dossier statique (index.html et un sous-dossier data/ chiffré) sans aucune base de données ni maintenance serveur. Vous pouvez simplement le glisser-déposer sur Cloudflare Pages (gratuit), Netlify Drop (gratuit), GitHub Pages, ou le transférer sur l'espace web de votre université par SFTP ou WebDAV.",
        portal_tech_q2_title: "Comment fonctionne le chiffrement local Zéro-Knowledge ?",
        portal_tech_q2_desc: "Chaque copie est chiffrée sur votre ordinateur en AES-256-GCM avec une clé aléatoire forte. Le serveur d'hébergement ne stocke que des fichiers chiffrés totalement inintelligibles (.enc). Même l'hébergeur ou un pirate informatique ne peut rien déchiffrer.",
        portal_tech_q3_title: "Pourquoi le lien magique 1-clic ne fait-il pas fuiter la clé ?",
        portal_tech_q3_desc: "Le lien magique est de la forme index.html?id=...#k=CLE_SECRETE. Selon le standard web mondial (RFC 3986), le fragment d'URL situé après le dièse (#) est strictement confiné au navigateur de l'étudiant et n'est JAMAIS envoyé au serveur dans les requêtes HTTP. Le déchiffrement se fait uniquement en mémoire vive.",

        // Pricing
        nav_pricing: "Tarifs",
        pricing_tag: "Tarification Claire",
        pricing_title: "Commencez gratuitement, passez à Pro pour le Portail Web et Excel",
        pricing_subtitle: "Corrigez tous vos examens avec l'IA gratuitement. Soutenez le développement et débloquez l'export Excel officiel, les copies PDF annotées et le Portail Web Étudiant avec Gradaly Pro.",
        plan_free_name: "Gradaly Gratuit",
        plan_free_badge: "Gratuit à vie",
        plan_free_period: "/ gratuit",
        plan_free_f1: "Modèles Gemini 3.8 & 3.7 Flash avec mode Free Tier",
        plan_free_f2: "Copies et étudiants illimités",
        plan_free_f3: "Appariement de la liste d'étudiants 100% hors-ligne",
        plan_free_f4: "Console de correction live & contrôle humain total",
        plan_free_f5: "Statistiques complètes et histogrammes de notes",
        plan_free_f6: "Exports d'évaluation (1 copie test en Excel, PDF et portail web)",
        plan_free_btn: "Télécharger gratuitement",
        plan_pro_name: "Gradaly Pro",
        plan_pro_badge: "Recommandé",
        plan_pro_period: "/ an (TTC)",
        plan_pro_f1: "Portail Web Étudiant Zéro-Knowledge (toute la classe, hébergement libre)",
        plan_pro_f2: "Exportation Excel multi-feuilles illimitée",
        plan_pro_f3: "Archive ZIP de toutes les copies PDF annotées",
        plan_pro_f4: "Page de garde récapitulative élégante (note, synthèse par question)",
        plan_pro_f5: "Licence valide sur toutes vos machines (macOS, Windows, Linux)",
        plan_pro_f6: "Mises à jour Pro et support prioritaire",
        plan_pro_btn: "Passer à Gradaly Pro (29,99 € / an)",
    }
};

document.addEventListener('alpine:init', () => {
    Alpine.data('i18n', () => ({
        lang: 'en',
        t: {},
        init() {
            // Check browser language or saved preference
            const userLang = navigator.language || navigator.userLanguage; 
            if(userLang.startsWith('fr')) {
                this.lang = 'fr';
            }
            this.updateTranslations();
        },
        toggleLang() {
            this.lang = this.lang === 'en' ? 'fr' : 'en';
            this.updateTranslations();
        },
        updateTranslations() {
            this.t = translations[this.lang];
        }
    }));
});
