const translations = {
    en: {
        nav_download: "Download App",
        hero_title1: "Grade Smarter, Not Harder.",
        hero_title2: "Your AI Grading Assistant.",
        hero_subtitle: "Spend your time designing a fine-grained, high-quality rubric rather than grading repetitively. Gradaly applies your criteria with AI, lets you instantly simulate the impact of adjustments across the entire cohort, and keeps you fully in control of every grade.",
        download_mac: "Download for macOS",
        see_how: "See how it works",
        phil_title: "Our Philosophy",
        phil_text: "Repetitive grading is exhausting and adds little pedagogical value. Teachers spend countless hours tallying marks instead of exercising pedagogical judgment. Gradaly shifts your time and expertise to where they truly matter: designing a rigorous, fine-grained evaluation rubric. By delegating systematic criteria checking to AI, you can easily simulate the impact of changing weights or criteria across the whole cohort, re-run grading in one click, and dedicate your energy to providing meaningful, personalized feedback to your students.",
        
        adv_title: "Why choose Gradaly?",
        adv_pedagogy_title: "Pedagogical Focus & Rubric Design",
        adv_pedagogy_text: "Invest your expertise in designing nuanced, high-standard evaluation rubrics instead of doing repetitive manual grading. AI systematically applies your criteria to every single copy.",
        adv_flex_title: "Dynamic Recalculation & Simulation",
        adv_flex_text: "Adjust a rubric weighting, tweak criteria, or change the base points: instantly observe the impact across the entire cohort or re-run grading in one click to test your evaluation scenarios.",
        adv_control_title: "You Have the Final Say",
        adv_control_text: "Gradaly is an assistant, not a replacement. The teacher retains full, sovereign control: validate, adjust criteria, or overwrite feedback with a single click.",
        adv_privacy_title: "Total Privacy & Zero Cloud",
        adv_privacy_text: "A student's name never leaves your computer. The CSV student roster, header inspection, and copy matching run 100% offline locally. Only cropped, anonymous answer snippets are analyzed by the AI.",
        adv1_title: "Native Desktop Experience",
        adv1_text: "Ultra-fast, lightweight, and responsive. Operates directly on your machine (macOS, Windows, Linux) with high-performance PDF rendering and zero browser lag.",
        adv_cost_title: "Direct Cost Control",
        adv_cost_text: "You own your Google Gemini API key. The application takes zero margin—whether you grade 10 or 1000 copies, you only pay direct provider costs (fractions of a cent per copy).",

        // Carousel slides
        carousel_slide0_badge: "Step 1: Canvas & Rubrics",
        carousel_slide0_title: "Layout, Maximum Score & Criteria",
        carousel_slide0_desc: "Delineate the student ID zone for offline OCR, configure question answer boxes, set individual maximum scores with automatic capping, and write custom AI prompts.",
        
        carousel_slide1_badge: "Step 2: Students",
        carousel_slide1_title: "Import Student Roster (CSV)",
        carousel_slide1_desc: "Load your enrolled class list (matricule IDs, names, emails). Student data remains 100% confidential and stored locally on your machine.",
        
        carousel_slide2_badge: "Step 3: Matching",
        carousel_slide2_title: "Automatic & Manual Copy Matching",
        carousel_slide2_desc: "Batch import scanned student copies. Local offline OCR matches each copy to the student record, with 1-click manual verification.",
        
        carousel_slide3_badge: "Step 4: Workspace",
        carousel_slide3_title: "Unified Grading Console",
        carousel_slide3_desc: "Navigate copies smoothly with a high-performance PDF viewer, switchable anonymous mode, rubric checklist, and direct access to Pro exports.",
        
        carousel_slide4_badge: "Step 5: Batch AI",
        carousel_slide4_title: "Launch AI Grading Across Copies",
        carousel_slide4_desc: "Select which questions and copies to grade using Google Gemini (3.8 Flash, 3.7 Flash, 3.1 Pro), with options to evaluate unrated copies or overwrite.",
        
        carousel_slide5_badge: "Step 5 (cont.): Progress",
        carousel_slide5_title: "Real-Time AI Execution & Feedback",
        carousel_slide5_desc: "Follow the multimodal AI in real time as it ticks validated criteria and drafts constructive feedback. You maintain full sovereignty to override anything.",
        
        carousel_slide6_badge: "Step 6: Analytics",
        carousel_slide6_title: "Cohort Statistics & Clarified Histograms",
        carousel_slide6_desc: "Track grade distributions and rubric success rates in real time. Histograms feature unambiguous interval notation [a, b) with hover inequalities.",
        
        carousel_slide7_badge: "PRO Feature: Annotated Copies",
        carousel_slide7_title: "Individual Student PDF Reports (ZIP)",
        carousel_slide7_desc: "Export all graded copies in one ZIP archive! Each student receives a print-friendly PDF featuring an executive summary cover sheet and interleaved corrections.",

        // Guide / User Guide Section
        guide_title: "Gradaly User Guide: From Rubric to Grade Export",
        guide_subtitle: "Gradaly simplifies and accelerates exam grading with the power of Gemini models, while keeping teachers in full control of every decision.",

        guide_step1_tag: "Step 1",
        guide_step1_title: "Evaluation Canvas & Rubric Design",
        guide_step1_subtitle: "Invest your time in crafting a precise, high-standard evaluation rubric on your exam sheet:",
        guide_step1_item1_title: "Identification Area:",
        guide_step1_item1_desc: "Delineate the reserved box for student details (name, first name, ID/matricule).",
        guide_step1_item2_title: "Question Layout:",
        guide_step1_item2_desc: "Add exam questions by drawing bounding boxes over the respective answer regions.",
        guide_step1_item3_title: "Detailed Criteria & Maximum Score:",
        guide_step1_item3_desc: "Define fine-grained additive criteria (0.5 pt increments), set individual question maximum scores with automatic capping, and ensure rubric consistency.",
        guide_step1_item4_title: "Evaluation Logic (Prompt):",
        guide_step1_item4_desc: "Write clear expectations, grading tolerances, and required steps to guide the AI with pedagogical precision.",

        guide_step2_tag: "Step 2",
        guide_step2_title: "Import Student Roster",
        guide_step2_subtitle: "Load your enrolled class list to prepare tracking and export:",
        guide_step2_item1_title: "CSV File:",
        guide_step2_item1_desc: "Import student records (matricule IDs, last names, first names, email addresses, groups).",
        guide_step2_item2_title: "Secure Local Reference:",
        guide_step2_item2_desc: "This roster stays 100% on your computer and serves as the official reference for matching copies.",

        guide_step3_tag: "Step 3",
        guide_step3_title: "Import Copies & Matching",
        guide_step3_subtitle: "Batch drop files and seamlessly connect them to students:",
        guide_step3_item1_title: "Batch PDF Drop:",
        guide_step3_item1_desc: "Import your scanned student exam PDF copies all at once.",
        guide_step3_item2_title: "Automatic Matching (100% Offline):",
        guide_step3_item2_desc: "Using a private on-device OCR algorithm, Gradaly inspects the identification box and matches each copy to the student record.",
        guide_step3_item3_title: "Ergonomic Manual Adjustment:",
        guide_step3_item3_desc: "If handwriting is ambiguous, inspect high-resolution zoomed headers and assign students in a single click.",

        guide_step4_tag: "Step 4",
        guide_step4_title: "AI-Assisted Grading & Human Control",
        guide_step4_subtitle: "The core strength of Gradaly:",
        guide_step4_item1_title: "Gemini Multimodal Analysis:",
        guide_step4_item1_desc: "The AI examines the student's handwritten answer according to your prompt, selects met criteria and suggests an instant score.",
        guide_step4_item2_title: "Constructive Feedback:",
        guide_step4_item2_desc: "Gradaly generates a personalized constructive comment explaining errors and successes to the student.",
        guide_step4_item3_title: "Complete Teacher Sovereignty:",
        guide_step4_item3_desc: "The AI is strictly an advisory assistant. The teacher remains the sole decision-maker: easily override, toggle criteria or polish comments.",

        guide_step5_tag: "Step 5",
        guide_step5_title: "Analytics, Simulation & Grade Export",
        guide_step5_subtitle: "Cohort oversight, simulation, and distribution of results:",
        guide_step5_item1_title: "Statistics & Clarified Histograms:",
        guide_step5_item1_desc: "Monitor completion rates, review cohort distributions with unambiguous interval brackets [a, b), and check criterion success rates.",
        guide_step5_item2_title: "Simulation & Dynamic Recalculation:",
        guide_step5_item2_desc: "Adjust rubric weights, modify criteria, or re-run grading: instantly observe the impact of your pedagogical decisions across the whole cohort.",
        guide_step5_item3_title: "Multi-Sheet Excel Export (PRO):",
        guide_step5_item3_desc: "Export comprehensive spreadsheets (summary with student IDs, names, emails, plus individual question sheets) ready for school administration.",
        guide_step5_item4_title: "Annotated Student PDFs in ZIP (PRO):",
        guide_step5_item4_desc: "Generate print-friendly individual PDF copies for each student with an executive summary cover sheet and interleaved corrections.",

        // Privacy Callout
        privacy_banner_title: "Local Architecture & Student Anonymity",
        privacy_banner_badge: "100% Offline",
        privacy_banner_desc: "A student's name never leaves your computer. The CSV student roster, header OCR, and copy matching operate entirely locally on your machine. Only cropped answer snippets defined in the canvas are sent to the AI via your own Gemini API key, ensuring students cannot be identified when the canvas is properly configured.",

        // Download & Gatekeeper
        download_mac: "Download for macOS",
        download_windows: "Download for Windows",
        download_linux: "Download for Linux",
        download_appimage: "Download .AppImage",
        download_deb: "Download .deb",
        download_sub: "Universal (Apple Silicon M1-M4 & Intel)",
        download_sub_mac: "Apple Silicon (M1-M4) & Intel",
        download_sub_windows: "Windows 10, 11 (64-bit)",
        download_sub_linux: "Ubuntu 22.04+, Debian 12+, Fedora",
        macos_req: "Requires macOS 11.0 or later",
        windows_req: "Requires Windows 10/11 (64-bit)",
        linux_req: "Requires 64-bit Linux (x86_64 or ARM64)",
        windows_badge: "64-bit Installer (.exe)",
        apple_notarized_badge: "Official Apple Developer Signed & Notarized",
        gatekeeper_btn: "Security & Installation info (macOS & Windows)",
        gatekeeper_title: "Security & Signature info",
        gatekeeper_desc: "On macOS, Gradaly is officially signed with an Apple Developer ID and notarized by Apple. On Windows, double-click the installer; if Windows Defender SmartScreen appears on first run, click 'More info' then 'Run anyway'.",
        gatekeeper_fix_title: "Quick start:",
        gatekeeper_step1: "Open the downloaded .dmg and drag Gradaly to Applications.",
        gatekeeper_step2: "Double-click Gradaly to launch. If prompted by macOS, click 'Open'.",
        gatekeeper_step3: "Launch Gradaly anytime from your Applications folder!",
        copy: "Copy",
        copied: "Copied!",
        cta_subtitle: "Join the teachers who have already reclaimed their weekends.",
        footer_rights: "All rights reserved.",

        // Pricing
        nav_pricing: "Pricing",
        pricing_tag: "Transparent Pricing",
        pricing_title: "Start Free, Upgrade for Multi-Sheet Excel & Annotated PDFs",
        pricing_subtitle: "Grade all your exams with AI for free. Support Gradaly and unlock official multi-sheet Excel exports and individual annotated student PDF packages with Gradaly Pro.",
        plan_free_name: "Gradaly Community",
        plan_free_badge: "Free Forever",
        plan_free_period: "/ free",
        plan_free_f1: "All AI models (Gemini Flash, Pro...)",
        plan_free_f2: "Unlimited students & exam copies",
        plan_free_f3: "100% offline student OCR & matching",
        plan_free_f4: "Live grading console & human control",
        plan_free_f5: "Cohort analytics & score histograms",
        plan_free_btn: "Download for Free",
        plan_pro_name: "Gradaly Pro",
        plan_pro_badge: "Recommended",
        plan_pro_period: "/ year",
        plan_pro_f1: "Unlimited Multi-Sheet Excel Export",
        plan_pro_f2: "Individual Annotated Student PDFs (ZIP Archive)",
        plan_pro_f3: "Print-friendly cover sheet with grade & question breakdown",
        plan_pro_f4: "License valid on all your machines (macOS, Windows, Linux)",
        plan_pro_f5: "Priority developer support & all future Pro updates",
        plan_pro_btn: "Get Gradaly Pro (29.99 € / yr)",
    },
    fr: {
        nav_download: "Télécharger l'App",
        hero_title1: "Corrigez plus intelligemment.",
        hero_title2: "Votre assistant IA pour la correction.",
        hero_subtitle: "Consacrez votre temps à concevoir un barème d'évaluation fin et rigoureux plutôt qu'à corriger de manière répétitive. Gradaly applique vos critères avec l'IA, simule immédiatement l'impact de vos ajustements sur toute la promotion et vous laisse toujours le dernier mot.",
        download_mac: "Télécharger pour macOS",
        see_how: "Voir le fonctionnement",
        phil_title: "Notre Philosophie",
        phil_text: "Corriger des copies de manière répétitive est épuisant et n'apporte que peu de valeur ajoutée. Gradaly permet à l'enseignant de déplacer son temps et son expertise là où ils comptent le plus : la conception d'un barème d'évaluation fin, juste et formateur. En confiant l'application systématique des critères à l'IA, vous pouvez tester vos barèmes, ajuster vos pondérations ou relancer une correction en mesurant immédiatement l'impact sur l'ensemble de la classe, et vous concentrer sur l'essentiel : les retours constructifs apportés à vos étudiants.",
        
        adv_title: "Pourquoi choisir Gradaly ?",
        adv_pedagogy_title: "Focus Pédagogique & Barème Fin",
        adv_pedagogy_text: "Consacrez votre expertise à la conception d'un barème d'évaluation fin, juste et exigeant plutôt qu'à répéter les mêmes gestes mécaniques. L'IA applique rigoureusement vos critères sur chaque copie.",
        adv_flex_title: "Simulation & Recalcul Dynamique",
        adv_flex_text: "Modifiez la pondération d'un critère, ajustez le barème ou la note de base : visualisez immédiatement l'impact sur toute la promotion ou relancez la correction en un clic pour tester vos scénarios.",
        adv_control_title: "Vous Gardez le Dernier Mot",
        adv_control_text: "Gradaly est une aide à la décision, pas un remplaçant. L'enseignant conserve un contrôle absolu : validez, modifiez un critère ou réécrivez un commentaire en un seul clic.",
        adv_privacy_title: "Confidentialité Absolue & Données Locales",
        adv_privacy_text: "Le nom d'un étudiant ne sort jamais de votre ordinateur. La liste des étudiants (CSV), la lecture des en-têtes et l'appariement des copies s'exécutent intégralement en local. Seuls des extraits de copies anonymisés sont analysés par l'IA.",
        adv1_title: "Application de Bureau Fluide",
        adv1_text: "Ultra-rapide, légère et réactive. S'exécute directement sur votre ordinateur (macOS, Windows, Linux) avec un affichage PDF haute performance, sans lenteur de navigateur ni distraction.",
        adv_cost_title: "Maîtrise Totale des Coûts",
        adv_cost_text: "Vous utilisez directement votre propre clé API Gemini sans intermédiaire. L'application ne prend aucune marge : corriger un examen complet ne vous coûte que quelques fractions de centime par copie.",

        // Carousel slides
        carousel_slide0_badge: "Étape 1 : Canevas & Barème",
        carousel_slide0_title: "Découpage, Score maximum & Critères",
        carousel_slide0_desc: "Délimitez la zone d'en-tête pour l'OCR local, cadrez les questions, fixez le score maximum par question avec plafonnement automatique et consignes IA.",
        
        carousel_slide1_badge: "Étape 2 : Étudiants",
        carousel_slide1_title: "Import de la Liste des Étudiants (CSV)",
        carousel_slide1_desc: "Chargez votre liste de classe ou de promotion (matricules, noms, emails). Aucune donnée nominative ne sort de votre machine : confidentialité 100% garantie.",
        
        carousel_slide2_badge: "Étape 3 : Appariement",
        carousel_slide2_title: "Appariement Automatique & Manuel",
        carousel_slide2_desc: "Importez vos copies PDF en lot. L'OCR local hors-ligne inspecte la zone d'en-tête manuscrite et associe chaque copie à son étudiant en un clic.",
        
        carousel_slide3_badge: "Étape 4 : Visualiseur",
        carousel_slide3_title: "Poste d'Évaluation Ergonomique",
        carousel_slide3_desc: "Parcourez les copies avec un visualiseur haute résolution, un mode anonyme commutable, la validation des critères et l'accès direct aux exports Pro.",
        
        carousel_slide4_badge: "Étape 5 : IA par lot",
        carousel_slide4_title: "Lancement de la Correction IA",
        carousel_slide4_desc: "Sélectionnez les questions et copies à évaluer avec Gemini (3.8 Flash, 3.7 Flash, 3.1 Pro), avec option d'évaluer les copies restantes ou tout réévaluer.",
        
        carousel_slide5_badge: "Étape 5 (suite) : Exécution",
        carousel_slide5_title: "Suivi en Direct & Retours Détaillés",
        carousel_slide5_desc: "Observez l'analyse multimodale en temps réel. Gemini coche les critères mérités et formule un commentaire constructif que l'enseignant valide ou modifie.",
        
        carousel_slide6_badge: "Étape 6 : Synthèse",
        carousel_slide6_title: "Statistiques & Histogrammes Clairs",
        carousel_slide6_desc: "Suivez la moyenne, la médiane et le taux de succès par critère. Testez l'impact de vos ajustements de barème sur toute la promotion grâce à des histogrammes clairs [a, b[.",
        
        carousel_slide7_badge: "Fonctionnalité PRO : Copies Annotées",
        carousel_slide7_title: "Export PDF Individuel avec Page de Garde",
        carousel_slide7_desc: "Exportez l'ensemble des copies dans une archive ZIP ! Chaque étudiant reçoit un PDF optimisé pour l'impression avec page de garde récapitulative et corrections entrelacées.",

        // Guide / User Guide Section
        guide_title: "Guide d'utilisation de Gradaly : Du barème à l'export des notes",
        guide_subtitle: "Gradaly simplifie et accélère la correction des copies grâce à la puissance des modèles Gemini, tout en laissant l'enseignant aux commandes de chaque décision.",

        guide_step1_tag: "Étape 1",
        guide_step1_title: "Conception du Barème et du Canevas",
        guide_step1_subtitle: "Prenez le temps de concevoir une grille d'évaluation fine et rigoureuse sur votre épreuve :",
        guide_step1_item1_title: "Zone d'identification :",
        guide_step1_item1_desc: "Délimitez l'emplacement réservé aux informations de l'étudiant (nom, prénom, numéro d'étudiant).",
        guide_step1_item2_title: "Découpage des questions :",
        guide_step1_item2_desc: "Ajoutez les questions de l'examen en traçant leurs zones de réponse sur le PDF vierge.",
        guide_step1_item3_title: "Critères précis & Score maximum :",
        guide_step1_item3_desc: "Définissez des critères d'évaluation fins et additifs (multiples de 0,5 pt), fixez le score maximum par question avec plafonnement automatique des points.",
        guide_step1_item4_title: "Consignes d'évaluation (Prompt) :",
        guide_step1_item4_desc: "Formulez les attentes pédagogiques, tolérances et étapes obligatoires pour guider l'analyse de l'IA avec rigueur.",

        guide_step2_tag: "Étape 2",
        guide_step2_title: "Import de la liste des étudiants",
        guide_step2_subtitle: "Chargez votre liste de classe pour préparer le suivi et l'attribution :",
        guide_step2_item1_title: "Fichier CSV :",
        guide_step2_item1_desc: "Importez les données de vos étudiants (identifiants, noms, adresses email, groupes).",
        guide_step2_item2_title: "Référence locale sécurisée :",
        guide_step2_item2_desc: "Ce fichier constitue la référence pour l'association ultérieure des copies et reste 100% stocké en local sur votre ordinateur.",

        guide_step3_tag: "Étape 3",
        guide_step3_title: "Import des copies et appariement (Matching)",
        guide_step3_subtitle: "Dépôt des fichiers et liaison automatique :",
        guide_step3_item1_title: "Dépôt des fichiers :",
        guide_step3_item1_desc: "Importez les PDF des copies d'étudiants scannées en lot.",
        guide_step3_item2_title: "Appariement automatique 100% hors-ligne :",
        guide_step3_item2_desc: "Grâce à un algorithme intelligent d'OCR local (0% cloud), Gradaly analyse la zone d'identification et relie automatiquement chaque copie à l'étudiant correspondant issu de votre fichier CSV.",
        guide_step3_item3_title: "Ajustement manuel :",
        guide_step3_item3_desc: "Si un doute persiste ou si l'écriture est illisible, vous pouvez finaliser l'appariement manuellement en quelques clics grâce à l'aperçu zoomé en haute résolution.",

        guide_step4_tag: "Étape 4",
        guide_step4_title: "Évaluation assistée par IA & Contrôle humain",
        guide_step4_subtitle: "C'est la force de Gradaly :",
        guide_step4_item1_title: "Analyse par Gemini :",
        guide_step4_item1_desc: "L'IA examine la réponse de l'étudiant selon vos instructions, sélectionne les critères validés et calcule une proposition de note.",
        guide_step4_item2_title: "Feedback constructif :",
        guide_step4_item2_desc: "Gradaly génère un retour explicatif personnalisé pour aider l'étudiant à comprendre ses erreurs et ses réussites.",
        guide_step4_item3_title: "Maîtrise totale par le correcteur :",
        guide_step4_item3_desc: "L'IA est un outil de support et d'aide à la décision. L'enseignant reste l'unique décideur : vous pouvez corriger manuellement, valider, modifier les critères sélectionnés ou retoucher le commentaire en toute liberté.",

        guide_step5_tag: "Étape 5",
        guide_step5_title: "Pilotage, Simulation & Exportation",
        guide_step5_subtitle: "Supervision analytique et diffusion des résultats :",
        guide_step5_item1_title: "Statistiques & Histogrammes clairs :",
        guide_step5_item1_desc: "Visualisez l'état d'avancement de votre correction et analysez les performances globales (histogrammes avec tranches [a, b[ rigoureuses, taux de succès par critère).",
        guide_step5_item2_title: "Simulation & Recalcul dynamique :",
        guide_step5_item2_desc: "Ajustez une pondération, modifiez le barème ou relancez l'évaluation : observez instantanément l'impact de vos choix pédagogiques sur l'ensemble de la classe.",
        guide_step5_item3_title: "Export Excel multi-feuilles (PRO) :",
        guide_step5_item3_desc: "Exportez l'ensemble des résultats (feuille récapitulative officielle et feuilles ordonnées par question) prêt pour votre scolarité.",
        guide_step5_item4_title: "Archive ZIP de copies PDF annotées (PRO) :",
        guide_step5_item4_desc: "Générez un ensemble de fichiers PDF individuels print-friendly avec page de garde récapitulative et pages de copie entrelacées.",

        // Privacy Callout
        privacy_banner_title: "Architecture locale & Anonymat des étudiants",
        privacy_banner_badge: "100% Hors-ligne",
        privacy_banner_desc: "Le nom d'un étudiant ne sort jamais de votre ordinateur. La liste des étudiants (CSV), la lecture des en-têtes et l'appariement des copies s'exécutent intégralement en local sur votre machine. Seuls des fragments de copies délimités dans le canevas partent vers l'IA via votre propre clé API Gemini, ne permettant en aucun cas d'identifier l'étudiant si le canevas a bien été configuré.",

        // Download & Gatekeeper
        download_mac: "Télécharger pour macOS",
        download_windows: "Télécharger pour Windows",
        download_linux: "Télécharger pour Linux",
        download_appimage: "Télécharger .AppImage",
        download_deb: "Télécharger .deb",
        download_sub: "Universel (Apple Silicon M1-M4 & Intel)",
        download_sub_mac: "Apple Silicon (M1-M4) & Intel",
        download_sub_windows: "Windows 10, 11 (64-bit)",
        download_sub_linux: "Ubuntu 22.04+, Debian 12+, Fedora",
        macos_req: "Requis : macOS 11.0 ou ultérieur",
        windows_req: "Requis : Windows 10/11 (64-bit)",
        linux_req: "Requis : Linux 64-bit (x86_64 ou ARM64)",
        windows_badge: "Installateur 64-bit (.exe)",
        apple_notarized_badge: "Certifié & Notarisé par Apple",
        gatekeeper_btn: "Informations de sécurité & installation (macOS & Windows)",
        gatekeeper_title: "Sécurité, Certificats & Lancement",
        gatekeeper_desc: "Sous macOS, Gradaly est officiellement signé avec un certificat Apple Developer ID Application et notarisé par Apple. Sous Windows, lancez l'installateur .exe ; si l'écran bleu Windows SmartScreen apparaît lors de la première ouverture, cliquez simplement sur « Informations complémentaires » puis « Exécuter quand même ».",
        gatekeeper_fix_title: "Démarrage rapide :",
        gatekeeper_step1: "Ouvrez le .dmg téléchargé et glissez Gradaly dans Applications.",
        gatekeeper_step2: "Double-cliquez pour ouvrir. Si macOS demande confirmation, cliquez simplement sur « Ouvrir ».",
        gatekeeper_step3: "Lancez Gradaly à tout moment depuis votre dossier Applications !",
        copy: "Copier",
        copied: "Copié !",
        cta_subtitle: "Rejoignez les enseignants qui ont déjà récupéré leurs week-ends.",
        footer_rights: "Tous droits réservés.",

        // Pricing
        nav_pricing: "Tarifs",
        pricing_tag: "Tarification Claire",
        pricing_title: "Commencez gratuitement, passez à Pro pour Excel et les PDFs",
        pricing_subtitle: "Corrigez tous vos examens avec l'IA gratuitement. Soutenez le développement et débloquez l'export Excel officiel ainsi que les copies PDF annotées avec Gradaly Pro.",
        plan_free_name: "Gradaly Gratuit",
        plan_free_badge: "Gratuit à vie",
        plan_free_period: "/ gratuit",
        plan_free_f1: "Tous les modèles IA (Gemini Flash, Pro...)",
        plan_free_f2: "Copies et étudiants illimités",
        plan_free_f3: "Appariement de la liste d'étudiants 100% hors-ligne",
        plan_free_f4: "Console de correction live & contrôle humain total",
        plan_free_f5: "Statistiques complètes et histogrammes de notes",
        plan_free_btn: "Télécharger gratuitement",
        plan_pro_name: "Gradaly Pro",
        plan_pro_badge: "Recommandé",
        plan_pro_period: "/ an (TTC)",
        plan_pro_f1: "Exportation Excel multi-feuilles illimitée",
        plan_pro_f2: "Archive ZIP de toutes les copies PDF annotées",
        plan_pro_f3: "Page de garde récapitulative élégante (note, synthèse par question)",
        plan_pro_f4: "Licence valide sur toutes vos machines (macOS, Windows, Linux)",
        plan_pro_f5: "Mises à jour Pro et support prioritaire",
        plan_pro_btn: "Passer à Gradaly Pro (29,99 € / an)",
    }
};

document.addEventListener('alpine:init', () => {
    Alpine.data('i18n', () => ({
        lang: 'en',
        t: {},
        init() {
            // Check browser language or saved preference
            const userLang = navigator.language || navigator.userLanguage; 
            if(userLang.startsWith('fr')) {
                this.lang = 'fr';
            }
            this.updateTranslations();
        },
        toggleLang() {
            this.lang = this.lang === 'en' ? 'fr' : 'en';
            this.updateTranslations();
        },
        updateTranslations() {
            this.t = translations[this.lang];
        }
    }));
});
